### ISSUE TITLE
Supercool milestone's TODOs:

### ISSUE THREAD

**Issue by quangbuule** [quangbuule/codepieces#1]
### Required
- [ ] User can login using GitHub or Google.
- [ ] User can have two accounts or more (e.g. 1 GitHub account, 1 Google account but same user).
- [ ] User can create snippets and use without authentication.
- [ ] User can sync snippets across machines.
- [ ] User can update snippets.
- [ ] User can hashtag snippets.

#### Optional
- [ ] User can create organizations.
